name: CI
on:
  pull_request:
    branches: 
      - main
  push: 
    branches:
      - main     
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: flutter-build
        name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
      - run: | 
          flutter pub get
          flutter build web
          sed -i "s|<base href=\".*\">|<base href=\"/flutter_namer/\">|g" build/web/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # The folder the action should deploy.
        
