name: CI
on:
  pull_request:
    branches: 
      - main
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: flutter-build
        name: Flutter build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.x'
          channel: 'stable'
      - run: | 
          flutter pub get
          flutter build web
          cp -r build/web _site
      - name: Configure pages
        uses: actions/configure-pages@v3
      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v1
        